import { useEffect, useRef, useState } from 'react'
import { AGENTS, type Agent } from '@/data/agents'
import { AgentAvatar } from '@/components/AgentAvatar'
import { X, Check, CornerDownLeft, Wallet, Lock } from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'

interface Props {
  agent: Agent | null
  connected: boolean
  onConnect: () => void
  onClose: () => void
  onSubmit: (agent: Agent, label: string) => void
}

/**
 * Try an agent capability. This does NOT pay a reward — see
 * server/app/routes/runs.py. What pays is holding $CLST.
 *
 * Dispatching is a wallet-scoped action (the run logs against your
 * address), so this modal gates on a connected wallet — the rest of the
 * app browses freely.
 */
export function RunModal({ agent, connected, onConnect, onClose, onSubmit }: Props) {
  const [picked, setPicked] = useState<Agent | null>(agent)
  const [brief, setBrief] = useState('')
  const [phase, setPhase] = useState<'pick' | 'done'>('pick')
  const listRef = useRef<HTMLDivElement>(null)

  useEffect(() => setPicked(agent), [agent])
  useEffect(() => {
    if (agent && listRef.current) {
      const el = listRef.current.querySelector(`[data-agent="${agent.id}"]`)
      el?.scrollIntoView({ block: 'nearest' })
    }
  }, [agent])

  const trimmed = brief.trim()
  const canSubmit = connected && !!picked && trimmed.length > 0

  const submit = () => {
    if (!picked || !trimmed || !connected) return
    onSubmit(picked, trimmed.length > 72 ? trimmed.slice(0, 72) + '…' : trimmed)
    setPhase('done')
    setTimeout(() => {
      setPhase('pick')
      setBrief('')
      onClose()
    }, 1400)
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.25 }}
      className="fixed inset-0 z-50 grid place-items-center p-4"
      style={{ background: 'rgba(23,23,23,0.5)' }}
      onClick={onClose}
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.94, y: 24 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.96, y: 12 }}
        transition={{ type: 'spring', stiffness: 340, damping: 28 }}
        className="card flex max-h-[86vh] w-[560px] max-w-full flex-col p-0"
        onClick={(e) => e.stopPropagation()}
      >
        <AnimatePresence mode="wait">
          {phase === 'done' ? (
            <motion.div
              key="done"
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ type: 'spring', stiffness: 320, damping: 20 }}
              className="flex flex-col items-center px-8 py-12"
            >
              <motion.span
                initial={{ scale: 0 }}
                animate={{ scale: 1 }}
                transition={{ type: 'spring', stiffness: 300, damping: 14, delay: 0.1 }}
                className="grid h-14 w-14 place-items-center rounded-full"
                style={{ background: 'var(--signal-dim)' }}
              >
                <Check size={26} style={{ color: 'var(--signal)' }} strokeWidth={2.6} />
              </motion.span>
              <p className="mt-4 text-[18px] font-medium">Dispatched to {picked?.name}</p>
              <p className="mt-1 t-small muted">Logged to your activity — no reward is generated by trying an agent.</p>
            </motion.div>
          ) : (
            <motion.div key="pick" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="flex min-h-0 flex-col">
              {/* header with the picked agent as identity */}
              <div className="flex items-start justify-between gap-4 px-6 pb-4 pt-6">
                <div className="flex items-center gap-3">
                  {picked ? (
                    <AgentAvatar agent={picked} size={44} />
                  ) : (
                    <span className="grid h-11 w-11 shrink-0 place-items-center rounded-full" style={{ background: 'var(--surface-raised)', border: '1px dashed var(--line-bright)' }}>
                      <CornerDownLeft size={16} style={{ color: 'var(--ink-soft)' }} />
                    </span>
                  )}
                  <div>
                    <h2 className="text-[19px] font-medium leading-tight">{picked ? `Run ${picked.name}` : 'Run an agent'}</h2>
                    <p className="t-small muted mt-0.5">{picked ? `${picked.category} · ${picked.trigger}` : 'Pick a capability first'}</p>
                  </div>
                </div>
                <motion.button
                  onClick={onClose}
                  whileHover={{ rotate: 90, scale: 1.08 }}
                  transition={{ type: 'spring', stiffness: 300, damping: 16 }}
                  className="icon-button shrink-0"
                >
                  <X size={18} />
                </motion.button>
              </div>

              {picked && (
                <p className="t-small muted border-t px-6 py-3.5" style={{ borderColor: 'var(--line)', background: 'var(--surface-raised)' }}>
                  {picked.blurb}
                </p>
              )}

              {/* agent picker — horizontal chips row, compact */}
              <div ref={listRef} className="flex gap-2 overflow-x-auto px-6 py-4">
                {AGENTS.map((a) => (
                  <motion.button
                    key={a.id}
                    data-agent={a.id}
                    onClick={() => setPicked(a)}
                    whileTap={{ scale: 0.96 }}
                    className="flex shrink-0 items-center gap-2 rounded-full border py-1.5 pl-1.5 pr-3.5 text-[13px] font-medium transition-colors"
                    style={
                      picked?.id === a.id
                        ? { borderColor: 'var(--signal)', background: 'var(--signal-dim)', color: 'var(--ink)' }
                        : { borderColor: 'var(--line)', color: 'var(--ink-soft)' }
                    }
                  >
                    <AgentAvatar agent={a} size={24} />
                    {a.name}
                  </motion.button>
                ))}
              </div>

              {/* brief input */}
              <div className="px-6">
                <div
                  className="rounded-2xl border transition-colors focus-within:border-[var(--signal)]"
                  style={{ borderColor: 'var(--line-bright)', background: 'var(--surface-raised)' }}
                >
                  <textarea
                    value={brief}
                    onChange={(e) => setBrief(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) submit()
                    }}
                    rows={3}
                    maxLength={500}
                    placeholder={picked ? `Give ${picked.name} a task… e.g. "scan ETH-USD liquidity for the week"` : 'Pick an agent above, then describe your task'}
                    className="w-full resize-none bg-transparent px-4 pt-3.5 text-[14.5px] outline-none placeholder:text-[var(--ink-soft)]"
                  />
                  <div className="flex items-center justify-between px-4 pb-2.5">
                    <span className="t-mono text-[11px]" style={{ color: 'var(--ink-soft)' }}>
                      {brief.length > 0 ? `${brief.length}/500` : '⌘↵ to dispatch'}
                    </span>
                    {connected ? (
                      <motion.button
                        onClick={submit}
                        disabled={!canSubmit}
                        whileHover={canSubmit ? { scale: 1.04 } : undefined}
                        whileTap={canSubmit ? { scale: 0.96 } : undefined}
                        className="pill pill-ink flex items-center gap-1.5"
                        style={{ height: '2rem', fontSize: 13, opacity: canSubmit ? 1 : 0.4, cursor: canSubmit ? 'pointer' : 'not-allowed' }}
                      >
                        Dispatch {picked ? picked.name : 'agent'} <CornerDownLeft size={13} />
                      </motion.button>
                    ) : (
                      <motion.button
                        onClick={onConnect}
                        whileHover={{ scale: 1.04 }}
                        whileTap={{ scale: 0.96 }}
                        className="pill pill-ink flex items-center gap-1.5"
                        style={{ height: '2rem', fontSize: 13 }}
                      >
                        <Wallet size={13} /> Connect to dispatch
                      </motion.button>
                    )}
                  </div>
                </div>
                {connected ? (
                  <p className="t-small mt-2.5 pb-6" style={{ color: 'var(--ink-soft)' }}>
                    Logged to your activity. Runs are recorded, not paid — what pays is holding $CLST.
                  </p>
                ) : (
                  <p className="t-small mt-2.5 flex items-center gap-1.5 pb-6" style={{ color: 'var(--ink-soft)' }}>
                    <Lock size={11} /> Dispatching logs the run to your wallet — browsing stays open without one.
                  </p>
                )}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </motion.div>
    </motion.div>
  )
}
